export const programConstants = {
  FETCH_PROGRAM_REQUEST: "FETCH_PROGRAM_REQUEST",
  FETCH_PROGRAM_SUCCESS: "FETCH_PROGRAM_SUCCESS",
  FETCH_PROGRAM_FAILURE: "FETCH_PROGRAM_FAILURE",
  
  PROGRAM_DETAIL_REQUEST: "PROGRAM_DETAIL_REQUEST",
  PROGRAM_DETAIL_SUCCESS: "PROGRAM_DETAIL_SUCCESS",
  PROGRAM_DETAIL_FAILURE: "PROGRAM_DETAIL_FAILURE",
}